name: directfromcenter
favicon: null
layout_spectrum: 0.49801
typography_spectrum: 0.50344
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0e1c'
    - '#ffffff'
    - '#191826'
    - '#0b071e'
    - '#1f1e2c'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
